[build-system]
requires = ["setuptools", "wheel", "setuptools-scm"]

[tool.setuptools_scm]
version_scheme = "guess-next-dev"

[metadata]
name = "opinionated"
version = "0.0.1"
description = "Add-on for Matplotlib to produce pretty hrbrtheme-like-plots plots"
author = "Maximilian Noichl"
author_email = "noichlmax@hotmail.co.uk"
license = "MIT"
long_description = "Add-on for Matplotlib to produce pretty hrbrtheme-like-plots plots"
home_page = "https://github.com/MNoichl/opinionated"
project_urls =
    Source = "https://github.com/MNoichl/opinionated"

[classifiers]
Framework :: Matplotlib
License :: OSI Approved :: MIT License
Programming Language :: Python :: 3

[options]
packages = ["opinionated"]
install_requires =
    matplotlib
    seaborn
zip_safe = False
include_package_data = True

[options.package_data]
opinionated = ["data/*.mplstyle"]
